EC_Django_Deployer/Account/urls.py
from django.urls import path
from .views import LoginView, ProfileView
from django.contrib.auth import views as auth_views
from django.conf import settings

app_name = "Account"

urlpatterns = [

    path("login/", LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

EC_Django_Deployer/ECDeploy/urls.py
from django.urls import path
from .views import (InstanceListView, InstanceCreateView,
                    InstanceDetailView, SuccessView, InstanceTerminateView,
                    get_instance_info)

app_name = "ECDeploy"

urlpatterns = [
    path("list/", InstanceListView.as_view(), name="list"),
    path("create/", InstanceCreateView.as_view(), name="create"),
    path("<int:pk>/detail/",  InstanceDetailView.as_view(), name="detail"),
    path("<int:pk>/terminate/", InstanceTerminateView.as_view(), name="terminate"),
    path("success/", SuccessView.as_view(), name="success"),

    # json url
    path("info/<slug:instance_name>/", view=get_instance_info, name="info"),
    # path("code/<slug:instance_name>/", view=update_code, name="code"),
]

EC_Django_Deployer/EC_Django_Deployer/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('ec-deploy/', include("ECDeploy.urls")),
    path('accounts/', include("Account.urls")),
]

EC_Django_Deployer/ECDeploy/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy


class Instance(models.Model):

    name = models.SlugField(max_length=50, unique=True)
    project_name = models.CharField(max_length=256)
    github_url = models.URLField(max_length=200)
    description = models.TextField(default="")
    instance_id = models.CharField(max_length=48, default=None, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    # domain = models.URLField(max_length=200, default=None, null=True)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse_lazy("ECDeploy:detail", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["-name"]

EC_Django_Deployer/ECDeploy/forms.py
from django import forms
from .models import Instance
from django.utils.translation import gettext_lazy as _


class InstanceForm(forms.ModelForm):

    class Meta:
        model = Instance
        fields = (
            "name",
            "project_name",
            "github_url",
            "description"
        )
        labels = {
            "name": _("Server Name"),
            "project_name": _("Django Projct Name"),
            "github_url": _("Github Url"),
            "description": _("Project Description"),
        }
        error_messages = {
            "name": {
                "required": _("Server name is required."),
                "unique": _("Server name exists already."),
            },
            "project_name": {
                "required": _("Project name is required."),
            },
            "github_url": {
                "required": _("Github url is required."),
            },
        }
        help_texts = {
            "name": _("The name of server to deploy django project."),
            "project_name": _("The name of django project. (Or the name of the directory where manage.py file locates.)"),
            "github_url": _("The Url of Github repository."),
            "description": _("The description of this project."),
        }

        widgets = {
            "name": forms.TextInput(attrs={
                "class": "form-control"
            }),
            "project_name": forms.TextInput(attrs={"class": "form-control"}),
            "github_url": forms.TextInput(attrs={"class": "form-control"}),
            "domain": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control editor", "rows": "3"}),
        }

EC_Django_Deployer/ECDeploy/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, TemplateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from .models import Instance
from .forms import InstanceForm
from pathlib import Path
import json
from .aws_ec2_script import (create_instance_by_template,
                             terminate_instance_by_name, read_user_data_script,
                             list_instance_by_name, list_all_instance)
from django.contrib.auth.mixins import LoginRequiredMixin


SCRIPT_PATH = Path(
    Path(__file__).resolve().parent,
    "userdata_boto3.sh"
)
EC2_TEMPLATE = "EC-Deploy-Template"


class InstanceListView(LoginRequiredMixin, ListView):
    ''' A view to list all EC2 instances '''

    model = Instance
    extra_context = {"title": "Django-EC2 Deployment",
                     "heading": "All Running EC2 Instances"}


class InstanceCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    ''' A view to create a new EC2 instance '''

    model = Instance
    form_class = InstanceForm
    # success_url = reverse_lazy("ECDeploy:success")
    success_message = 'Instance "%(name)s" was created successfully. Waiting for AWS to response.'
    template_name = "ECDeploy/instance_form.html"
    extra_context = {"title": "Create new EC2 Instance",
                     "heading": "Django Easy Deployment"}

    def post(self, request, *args, **kwargs):

        form = self.form_class(request.POST)
        if form.is_valid():

            # Creates new instance record
            obj, created = Instance.objects.update_or_create(
                name=form.cleaned_data["name"],
                github_url=form.cleaned_data["github_url"],
                project_name=form.cleaned_data["project_name"],
                description=form.cleaned_data["description"],
            )

            # try:
            # Generates bash script based on given parameters.
            user_data = read_user_data_script(
                SCRIPT_PATH,
                form.cleaned_data["project_name"],
                form.cleaned_data["github_url"],
            )

            # Creates an new EC2 instance
            ec2 = create_instance_by_template(
                EC2_TEMPLATE,
                form.cleaned_data["name"],
                user_data
            )

            # get the instance id when it is created
            obj.instance_id = ec2[0]["instance_id"]

            # update the instance id with record
            obj.save()
            # except Exception as err:
            #     print(f"{err}")

            # redirect to the detail page
            return redirect("ECDeploy:detail", pk=obj.pk)

        return render(request, self.template_name, {"form": form})


class SuccessView(LoginRequiredMixin, TemplateView):
    ''' A view to display success message. '''

    template_name = "ECDeploy/success.html"
    extra_context = {"title": "Success",
                     "heading": "Success"}


class InstanceDetailView(LoginRequiredMixin, DetailView):
    ''' A view for details of a specified instance '''

    model = Instance
    extra_context = {"title": "EC2 Instance Detail Info",
                     "heading": "EC2 Instance Detail"}


class InstanceTerminateView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    ''' A view to terminate a specified instance '''

    model = Instance
    success_url = reverse_lazy("ECDeploy:success")
    # define a success message to display
    success_message = 'Instance "%(name)s" was terminated successfully. Waiting for AWS to response.'
    extra_context = {"title": "Terminate EC2 Instance",
                     "heading": "Terminate EC2 Instance"}

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            name=self.object.name,
        )

    def form_valid(self, form):
        # if valid, calls terminate function.
        # try:
        terminate_instance_by_name((self.object.name,))
        # except Exception as err:
        #     print(f"{err}")
        return super().form_valid(form)


def get_instance_info(request, instance_name):
    ''' A Json response to retrieve an instance info '''

    try:
        print(instance_name)
        ec2_list = list_instance_by_name((instance_name,))
        print(ec2_list)
        return JsonResponse({'status': 'success', 'data': json.dumps(ec2_list)}, status=200)
    except Exception as ex:
        return JsonResponse({'status': 'error', 'error': ex}, status=404)


# def get_all_instance_info(request, instance_name):
#     ''' A Json response to retrieve all instances info '''

#     try:
#         print(instance_name)
#         ec2_list = list_all_instance()
#         print(ec2_list)
#         return JsonResponse({'status': 'success', 'data': json.dumps(ec2_list)}, status=200)
#     except Exception as ex:
#         return JsonResponse({'status': 'error', 'error': ex}, status=404)

EC_Django_Deployer/ECDeploy/templates/ECDeploy/instance_confirm_delete.html
{% extends "layout/base.html" %} {% block main %}

<div class="container">
  <header class="text-center">
    <h3 class="h3 pt-4">{{heading}}</h3>
  </header>
  <hr class="my-2" />
  <div class="container p-5">
    <form method="post">
      {% csrf_token %}
      <p class="fs-4 py-3" style="min-height: 50vh">
        Are you sure you want to delete instance "{{ object }}"?
      </p>
      {{form}}
      <hr class="my-4" />
      <div class="d-flex py-2">
        <a
          class="btn btn-outline-secondary rounded-pill me-auto"
          href="{% url 'ECDeploy:detail' object.pk %}"
        >
          Back
        </a>
        <button class="btn btn-outline-danger rounded-pill mx-2" type="submit">
          Terminate
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

EC_Django_Deployer/ECDeploy/templates/ECDeploy/instance_detail.html
{% extends "layout/base.html" %} {% block main %}

<div class="container">
  <header class="text-center">
    <h3 class="h3 pt-4">{{heading}}</h3>
  </header>
  <hr class="my-2" />
  <div class="fliud-container font-monospace">
    <div class="row g-5 py-4">
      <div class="col-md-4 col-sm-12">
        <div class="card h-100">
          <h4 class="card-header">
            Server Name:
            <span id="name" class="fw-bold">{{instance.name}}</span>
          </h4>
          <div class="card-body">
            <h5 class="card-title mb-3">
              Project:
              <span id="project_name" class="fw-bold">
                {{instance.project_name}}
              </span>
              <a
                href="{{instance.github_url}}"
                class="card-link fs-6"
                target="_blank"
              >
                Github
              </a>
            </h5>
            <p class="card-text">
              Server ID:
              <span id="instance_id" class="fw-bold">
                {{instance.instance_id}}
              </span>
            </p>

            <p class="card-text">
              Create Date:
              <span id="created_date" class="fw-bold">
                {{instance.created_date|date:"Y-m-d H:i:s " }}
              </span>
            </p>
            <p class="card-text">
              Pulic IP:
              <span id="public_ip" class="fw-bold">
                <!-- public ip -->
              </span>
            </p>
            <p class="card-text">
              Status:
              <span id="status" class="fw-bold">
                <!-- status -->
              </span>
            </p>
            <p class="card-text">
              Description:
              <span id="status" class="">
                {{instance.description|safe}}
              </span>
            </p>
            <p>
              <button
                id="btn_update_state"
                type="button"
                class="btn btn-sm btn-outline-primary rounded-pill align-middle my-2"
              >
                <i class="bi bi-arrow-clockwise"></i>
                Refresh Instance State
              </button>
              <button
                id="btn_update_code"
                type="button"
                class="btn btn-sm btn-outline-success rounded-pill align-middle my-2"
                disabled
              >
                <i class="bi bi-cloud-upload"></i>
                Update Github Code
              </button>
            </p>
            <!-- <a
              id="btn_stop"
              href="#"
              class="btn btn-sm btn-outline-warning rounded-pill me-2"
              stop_ec2_by_name
            >
              Stop Instance
            </a> -->
            <hr class="py-2" />
            <div class="d-flex">
              <a
                href="{% url 'ECDeploy:list' %}"
                class="btn btn-sm btn-outline-secondary rounded-pill me-auto"
              >
                Back
              </a>

              <a
                href="{% url 'ECDeploy:terminate' instance.pk %}"
                class="btn btn-sm btn-outline-danger rounded-pill"
              >
                Terminate Instance
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8 col-sm-12">
        <img
          src="https://miro.medium.com/v2/resize:fit:1100/format:webp/0*wGZaCDK7BVhaKbeW.jpeg"
          alt=""
          srcset=""
        />
      </div>
    </div>
  </div>
</div>
{% load static %}
<!-- <script src="{% static 'js/main.js' %}"></script> -->
<script>
  const INFO_URL = "/ec-deploy/info";
  const UPDATE_CODE_URL = "/ec-deploy/code";
  const INSTANCE_NAME = "{{instance.name|safe}}";

  /**
   * Send a request to aws, the request is controled by the url
   * @param {*} name Instance name
   * @param {*} url Url defined by django.
   * @returns The json data returned by django.
   */
  const request_ec2_by_name = async (name, url) => {
    console.log(`${url}/${name}`);
    const json_data = await fetch(`${url}/${name}`).then((response) =>
      response.json()
    );
    return json_data;
  };

  /**
   * Displays instance info in the page
   * @param {*} data Json data of instance info
   */
  function display(data) {
    if (data["status"] == "success") {
      data = JSON.parse(data["data"])[0];
      console.log(data);
      $("#instance_id").text(data["instance_id"]);
      if (data["public_ip"]) {
        $("#public_ip").html(
          `<a href="http://${data["public_ip"]}" target="_blank">${data["public_ip"]}</a>`
        );
      }
      $("#status").text(data["status"]);
      if (data["status"] == "running") {
        $("#status").addClass("text-success");
      }
    } else {
      $("#status").addClass("text-secondary");
    }
  }

  // load instance info when document is ready.
  $(function () {
    request_ec2_by_name(INSTANCE_NAME, INFO_URL).then((data) => display(data));
  });

  // load instance info when refresh button is clicked.
  $("#btn_update_state").click(() => {
    request_ec2_by_name(INSTANCE_NAME, INFO_URL).then((data) => display(data));
  });

  // // update codes from github after deployed.
  // $("#btn_update_code").click(() => {
  //   request_ec2_by_name(INSTANCE_NAME, UPDATE_CODE_URL).then((data) =>
  //     console.log(data)
  //   );
  // });
</script>
{% endblock %}

EC_Django_Deployer/ECDeploy/templates/ECDeploy/instance_form.html
{% extends "layout/base.html" %} {% block main %}

<div class="container">
  <header class="text-center">
    <h3 class="h3 pt-4">{{heading}}</h3>
    <p class="lead">
      This is a demo of deploying a Django web application from Github
      repository on an AWS EC2 Instance. <br />
      Django Easy Deploy enables developers to streamline the deployment of
      their projects publicly in one click.
    </p>
  </header>
  <hr class="my-2" />
  {{form.errors}}
  <div class="container p-4">
    <form class="row g-4" method="post" novalidate>
      {% csrf_token %}
      <h4 class="mb-3">Server and Django Project Configuration</h4>

      <!-- name -->
      <div class="col-md-5 col-sm-12">
        <label class="form-label" for="{{ form.name.id_for_label }}">
          {{form.name.label}}
        </label>
        {{form.name}}
        <small class="form-text">Hint: {{form.name.help_text}} </small>
        <small class="text-danger"> {{form.name.errors}} </small>
      </div>

      <!-- project_name -->
      <div class="col-md-6 col-sm-12">
        <label class="form-label" for="{{ form.project_name.id_for_label }}">
          {{form.project_name.label}}
        </label>
        {{form.project_name}}
        <small class="form-text">Hint: {{form.project_name.help_text}} </small>
        <small class="text-danger"> {{form.project_name.errors}} </small>
      </div>

      <!-- github_url -->
      <div class="col-md-8 col-sm-12">
        <label class="form-label" for="{{ form.github_url.id_for_label }}">
          {{form.github_url.label}}
        </label>
        {{form.github_url}}
        <small class="form-text">Hint: {{form.github_url.help_text}} </small>
        <small class="text-danger"> {{form.github_url.errors}} </small>
      </div>

      <!-- description -->
      <div class="col-md-12 col-sm-12">
        <label
          class="form-label col-12"
          for="{{ form.github_url.id_for_label }}"
        >
          {{form.description.label}}
        </label>
        {{form.description}}
        <small class="form-text">Hint: {{form.description.help_text}} </small>
        <small class="text-danger"> {{form.description.errors}} </small>
      </div>

      <hr class="my-4" />

      <h4 class="mb-3">MySQL Configuration (Coming soon)</h4>

      <hr class="my-4" />

      <div class="d-flex py-2">
        <a
          class="btn btn-outline-secondary rounded-pill me-auto"
          href="{% url 'ECDeploy:list' %}"
        >
          Back
        </a>
        <button
          class="btn btn-outline-secondary rounded-pill mx-2"
          type="reset"
        >
          Reset
        </button>
        <button class="btn btn-outline-primary rounded-pill mx-2" type="submit">
          Create
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %} {% block js %}
<script>
  tinymce.init({
    selector: ".editor",
  });
</script>
{% endblock %}

EC_Django_Deployer/ECDeploy/templates/ECDeploy/instance_list.html
{% extends "layout/base.html" %} {% block main %}
<div class="container">
  <header class="d-flex align-items-center mt-2">
    <h3 class="h3 pt-4 me-auto">{{heading}}</h3>
    <a
      href="{% url 'ECDeploy:create' %}"
      class="btn btn-outline-primary rounded-pill"
    >
      Create
    </a>
  </header>
  <hr class="my-2" />
  <div class="row">
    <div class="col-sm-12">
      {% if instance_list %}
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">No</th>
            <th scope="col">Instance Name</th>
            <th scope="col">Project Name</th>
            <th scope="col">Create Time</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          {% for instance in instance_list %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>
              <a href="{% url 'ECDeploy:detail' instance.pk %}">
                {{ instance.name }}
              </a>
            </td>
            <td>{{ instance.project_name }}</td>
            <td>{{ instance.created_date|date:"Y-m-d H:i:s" }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p>No available instance in the list.</p>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

EC_Django_Deployer/ECDeploy/templates/ECDeploy/success.html
{% extends "layout/base.html" %} {% block main %}

<div class="container">
  <header class="text-center">
    <h3 class="h3 pt-4">{{heading}}</h3>
  </header>
  <hr class="my-2" />
  <div class="row p-4">
    <div class="col-12 font-monospace fs-4">
      {% if messages %} {% for message in messages %} 
      {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
      <p>{{ message }}</p>
      {% endif %} {% endfor %} {% endif %}
      <p>Back to <a href="{% url 'ECDeploy:list' %}"> Instance List</a></p>
    </div>
  </div>
</div>
{% endblock %}