EC_Django_Deployer/Account/urls.py
from django.urls import path
from .views import LoginView, ProfileView
from django.contrib.auth import views as auth_views
from django.conf import settings

app_name = "Account"

urlpatterns = [

    path("login/", LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
]

EC_Django_Deployer/ECDeploy/urls.py
from django.urls import path
from .views import (InstanceListView, InstanceCreateView,
                    InstanceDetailView, SuccessView, InstanceTerminateView,
                    get_instance_info)

app_name = "ECDeploy"

urlpatterns = [
    path("list/", InstanceListView.as_view(), name="list"),
    path("create/", InstanceCreateView.as_view(), name="create"),
    path("<int:pk>/detail/",  InstanceDetailView.as_view(), name="detail"),
    path("<int:pk>/terminate/", InstanceTerminateView.as_view(), name="terminate"),
    path("success/", SuccessView.as_view(), name="success"),

    # json url
    path("info/<slug:instance_name>/", view=get_instance_info, name="info"),
    # path("code/<slug:instance_name>/", view=update_code, name="code"),
]

EC_Django_Deployer/EC_Django_Deployer/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('ec-deploy/', include("ECDeploy.urls")),
    path('accounts/', include("Account.urls")),
]

EC_Django_Deployer/templates/layout/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>
    <!-- bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <!-- TinyMCE -->
    <script
      src="https://cdn.tiny.cloud/1/vy5wrj8ki5mcju47s2qsm9wb75q4yt6cerdf7e58o6iy0su4/tinymce/6/tinymce.min.js"
      referrerpolicy="origin"
    ></script>
    <!-- Bootstrap Icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    />
    <!-- jQuery -->
    <script
      src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
      integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
      crossorigin="anonymous"
    ></script>
    {% block css %}{% endblock %}
  </head>
  <body>
    {% include "layout/navbar.html" %} {% block main %}{% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
    {% block js %}{% endblock %}
  </body>
</html>

EC_Django_Deployer/templates/layout/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom border-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Argus Watcher</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Project
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'ECDeploy:list' %}">
                Django Easy Deploy
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="https://www.canva.com/design/DAFw0ioeJb0/GO9nyKOWYBuVMNn7SS4nkQ/view?utm_content=DAFw0ioeJb0&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink"
            >About Us
          </a>
        </li>
      </ul>

      {% if not user.is_authenticated %}
      <a class="btn btn-sm btn-warning" href="{% url 'Account:login' %}"
        >Login</a
      >
      {% else %}
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item dropstart">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="bi bi-person-circle"></i>
          </a>
          <ul class="dropdown-menu">
            <li><h6 class="dropdown-header">{{user.username}}</h6></li>
            <li>
              <a class="dropdown-item" href="{% url 'Account:profile' %}"
                >Profile</a
              >
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="{% url 'Account:logout' %}"
                >Logout</a
              >
            </li>
          </ul>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>